config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies, param: :slug
  resources :genres
  resources :movies do
    resources :reviews
    resources :favorites
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'user/:id' => 'users#show', as: :user

  # Defines the root path route ("/")
  # root "posts#index"
  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  before_validation :set_slug

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :genres
  has_many :favorites, dependent: :destroy
  has_many :fans, through: :favorites, source: :user

  validates :title, presence: true, uniqueness: true
  validates :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, allow_blank: true, format: {
    with: /\.(gif|jpg|png)\Z/i,
    message: 'must reference a GIF, JPG, or PNG image'
  }

  RATINGS = %w[G PG PG-13 R NC-17]

  scope :released, -> { where('released_on <= ?', Time.now).order('released_on desc') }
  scope :upcoming, -> { where('released_on > ?', Time.now).order('released_on asc') }
  scope :recent, ->(max = 5) { released.limit(max) }

  def flop?
    nil if reviews.count > 50 && average_stars >= 4
    total_gross.blank? || total_gross < 225_000_000
  end

  def average_stars
    reviews.average(:stars) || 0.0
  end

  private

  def set_slug
    self.slug = title.parameterize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  STARS = [1, 2, 3, 4, 5]

  validates :comment, length: { minimum: 4 }
  validates :stars, inclusion: { in: STARS, message: 'must be between 1 and 5' }

  def stars_as_percent
    (stars / 5.0) * 100.0
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :liked_movies, through: :favorites, source: :movie

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :current_user_admin?

  def require_signin
    return if current_user

    session[:intended_url] = request.url
    redirect_to new_user_session_url, danger: 'Please sign in first!'
  end

  def current_user_admin?
    current_user&.admin?
  end

  def require_admin
    return if current_user_admin?

    redirect_to root_url, alert: 'Unauthorized access!'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_signin
  before_action :set_movie

  def create
    @movie.fans << current_user
    redirect_to @movie, notice: 'Thanks for favorting!'
  end

  def destroy
    movie = current_user.liked_movies.find(params[:movie_id])
    current_user.liked_movies.destroy(movie)
    redirect_to @movie, notice: 'Sorry you unfaved it!'
  end

  private

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_signin, except: %i[index show]
  before_action :require_admin, except: %i[index show]
  before_action :set_movie, only: %i[show edit destroy update]

  def index
    @movies = case params[:filter]
              when 'upcoming'
                Movie.upcoming
              when 'recent'
                Movie.recent
              else
                Movie.released
              end
  end

  def show
    @genres = @movie.genres
    @fans = @movie.fans
    @favorite = current_user.favorites.find_by(movie: @movie) if current_user
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie successfully created!'
    else
      render :new, status: unprocessable_entity
    end
  end

  def edit; end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie successfully updated!'
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, status: :see_other, alert: 'Movie successfully deleted!'
  end

  private

  def set_movie
    @movie = Movie.find_by!(slug: params[:slug])
  end

  def movie_params
    params.require(:movie).permit(
      :title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name, genre_ids: []
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_signin, only: %i[new create]
  before_action :set_movie

  def new
    @review = Review.new
  end

  def index
    @reviews = @movie.reviews
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to movie_path(@movie), notice: 'Thanks for your review!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:stars, :comment)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @liked_movies = @user.liked_movies
    @reviews = @user.reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def fave_or_unfave_button(movie, favorite)
    if favorite
      button_to '♡ Unfave', movie_favorite_path(movie, favorite), method: :delete
    else
      button_to '♥️ Fave', movie_favorites_path(movie)
    end
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    return 'Flop' if movie.flop?

    number_to_currency(movie.total_gross, precision: 0)
  end

  def average_stars_percent(movie)
    movie.average_stars * 20
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/show.html.erb
<% @genre.movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag(movie.image_file_name) %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie_path(movie) %>
      </h2>
      <h3>
        <%= number_to_currency(movie.total_gross) %>
      </h3>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; <%= Time.now.year %> Your Company Name. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png", alt: "logo"), root_path %>
    <ul class="left">
      <li><%= link_to "Released", movies_path %></li>
      <li><%= link_to "Upcoming", filtered_movies_path("upcoming") %></li>
      <li><%= link_to "Recent", filtered_movies_path("recent") %></li>
    </ul>
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, user_path(current_user) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <%= render "layouts/flash" %>

      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>

  <%= render "shared/errors", object: movie %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10 %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.select :rating, Movie::RATINGS, prompt: "Pick one" %>
  </div>

  <div class="field">
    <%= form.label :total_gross %>
    <%= form.number_field :total_gross %>
  </div>

  <div class="field">
    <%= form.label :released_on %>
    <%= form.date_field :released_on %>
  </div>

  <div class="field">
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="field">
    <%= form.label :image_file_name %>
    <%= form.text_field :image_file_name, placeholder: "placeholder.png" %>
  </div>

  <div class="checkboxes">
    <%= form.collection_check_boxes(:genre_ids, Genre.order(:name), :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie: <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag(movie.image_file_name) %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie_path(movie.slug) %>
      </h2>
      <h3>
        <%= number_to_currency(movie.total_gross) %>
      </h3>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
  </section>
<% end %>

app/views/movies/new.html.erb
<h1>Create a New movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="image">
    <%= image_tag @movie.image_file_name %>

    <% if user_signed_in? %>
      <div class="faves">
        <%= fave_or_unfave_button(@movie, @favorite) %>
        <div class="count">
          <%= @fans.size %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="details">
    <h1><%= @movie.title %></h1>
    <p>
      <strong>Ratings:</strong>
      <%= @movie.rating %>
    </p>

    <div class="reviews">
      <h2>Reviews</h2>
      <% if @movie.reviews.blank? %>
        <p>There are no reviews yet.</p>
      <% else %>
        <%= render "shared/stars", percent: average_stars_percent(@movie) %>
      <% end %>
      <%= link_to pluralize(@movie.reviews.size, "review"), movie_reviews_path(@movie) %>
    </div>

    <p>
      <%= truncate(@movie.description, length: 250, separator: ' ') %>
    </p>

    <table>
      <tr>
        <th>Director:</th>
        <td><%= @movie.director %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= @movie.duration %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= @movie.total_gross %></td>
      </tr>
    </table>
    <%= link_to "Write Review", new_movie_review_path(@movie), class: "review" %>
  </div>

  <aside>
    <% if @fans.present? %>
      <h4>Fans</h4>
      <ul>
      <% @fans.each do |fan| %>
        <li><%= link_to fan.name, fan %></li>
      <% end %>
      </ul>
    <% end %>
  </aside>

  <aside>
    <% if @genres.present? %>
      <h4>Genres</h4>
      <ul>
      <% @genres.each do |genre| %>
        <li><%= link_to genre.name, genre %></li>
      <% end %>
      </ul>
    <% end %>
  </aside>

  <% if current_user_admin? %>
    <section class="admin">
      <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
      <%= link_to "Delete", movie_path(@movie), data: { turbo_method: :delete,  turbo_confirm: "Are you sure?" }, class: "button" %>
    </section>
  <% end %>

</section>

app/views/reviews/index.html.erb
<h1> Reviews for <%= link_to @movie.title, @movie %> </h1>
<ul class="reviews">
  <% @reviews.each do |review| %>
    <li>
      <%= pluralize(review.stars, 'star') %>
      <p>
        <%= link_to review.user.name, review.user %>
        <%= render "shared/stars", percent: review.stars_as_percent %>
        <span class="data">
          <%= time_ago_in_words(review.created_at) %> ago
        </span>
      </p>
      <p>
        <%= review.comment %>
      </p>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>New review for <%= link_to @movie.title, @movie %></h1>

<%= form_with(model: [@movie, @review]) do |f| %>
  <%= render "shared/errors", object: @review %>

  <%= f.label :stars %>
  <% Review::STARS.each do |star| %>
    <span class="star">
      <%= f.radio_button :stars, star %>
      <%= label_tag star %>
    </span>
  <% end %>

  <%= f.label :comment %>
  <%= f.text_area :comment, placeholder: "What did you think?" %>

  <%= f.submit "Post Review" %>

<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>

  <% if @user == current_user %>
    <div class="actions">
      <%= link_to "Edit Account", edit_user_registration_path, class: "button edit" %>
      <%= link_to "Delete Account", user_registration_path,  data: { turbo_method: :delete, turbo_confirm: "Permanently delete your accout!?" }, class: "button delete" %>
    </div>
  <% end %>

  <% if @reviews.present? %>
    <h3>Reviews</h3>
    <% @reviews.each do |review| %>
      <div class="review">
        <div class="details">
          <span class="title">
            <%= link_to review.movie.title, review.movie %>
          </span>
          <%= pluralize(review.stars, 'star') %>
          <span class="date">
            <%= time_ago_in_words(review.created_at) %> ago
          </span>
          <p>
            <%= review.comment %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if @liked_movies.present? %>
    <h3>Liked Movies</h3>
    <div class="favorite-movies">
      <% @liked_movies.each do |movie| %>
        <%= link_to image_tag(movie.image_file_name), movie %>
      <% end %>
    </div>
  <% end %>
</section>